package com.saby.personalportfolio

import android.os.Bundle
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
// This class is generated by `gomobile bind` from mobile/bridge/bridge.go
// during the CI build — it does not exist in this source tree until then.
import com.ledger.bridge.Bridge

// This entire screen exists to answer ONE question: does the whole chain
// (Go code -> gomobile bind -> .aar -> Kotlin -> compiled APK) actually
// work end to end? If this shows "bridge ok", it does. Nothing else about
// the real app (CAS import, holdings, XIRR, allocation) is built yet —
// see PROJECT_HANDOFF.md and the chat this came from for what's next.
class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val statusView = findViewById<TextView>(R.id.statusText)
        val result = try {
            Bridge.ping()
        } catch (e: Throwable) {
            "bridge call failed: ${e.message}"
        }
        statusView.text = "Go bridge says: \"$result\""
    }
}
